@BabyTracker_HostAddress = http://localhost:5064



### Baby

GET {{BabyTracker_HostAddress}}/api/Baby/
Accept: application/json

###

GET {{BabyTracker_HostAddress}}/api/Baby/2
Accept: application/json

###

POST {{BabyTracker_HostAddress}}/api/Baby/
Content-Type: application/json

{
    "name": "Racoo",
    "age": 2
}

###

PUT {{BabyTracker_HostAddress}}/api/Baby/3
Content-Type: application/json

{
    "id": 3,
    "name": "Racoo 3+",
    "age": 40
}

###

DELETE {{BabyTracker_HostAddress}}/api/Baby/3



### Tracker

GET {{BabyTracker_HostAddress}}/api/Tracker/
Accept: application/json



###
GET {{BabyTracker_HostAddress}}/api/Tracker/2

###

GET {{BabyTracker_HostAddress}}/api/Tracker/1
Accept: application/json

###

POST {{BabyTracker_HostAddress}}/api/Tracker/
Content-Type: application/json

{
    "babyId": 1,
    "milk": 100,
    "food": "Test",
    "foodAmount": 100,
    "poop": true
}

###

PUT {{BabyTracker_HostAddress}}/api/Baby/3
Content-Type: application/json

{
    "id": 3,
    "name": "Racoo 3+",
    "age": 40
}

###

DELETE {{BabyTracker_HostAddress}}/api/Baby/2




### Baby with tracker

POST {{BabyTracker_HostAddress}}/api/Baby/
Content-Type: application/json

{
    "name": "NewBaby",
    "age": 3
}

###

POST {{BabyTracker_HostAddress}}/api/Tracker/
Content-Type: application/json

{
    "babyId": 2,
    "milk": 100,
    "food": "Test",
    "foodAmount": 100,
    "poop": true
}



###
GET {{BabyTracker_HostAddress}}/api/Baby/2

###
GET {{BabyTracker_HostAddress}}/api/Tracker/2